/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.xbase.ui.hover.XbaseHoverProvider;
import org.xtext.labs.ui.AbstractMydslUiModule;
import org.xtext.labs.ui.contentassist.MydslHoverProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MydslUiModule extends AbstractMydslUiModule {
  public Class<? extends XbaseHoverProvider> bindXbaseHoverProvider() {
    return MydslHoverProvider.class;
  }
  
  public MydslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
