/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.mydsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Body Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.labs.mydsl.MydslPackage#getBodyStatement()
 * @model
 * @generated
 */
public interface BodyStatement extends EObject
{
} // BodyStatement
