/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.mydsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>bool Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.labs.mydsl.boolRef#getVarRef <em>Var Ref</em>}</li>
 * </ul>
 *
 * @see org.xtext.labs.mydsl.MydslPackage#getboolRef()
 * @model
 * @generated
 */
public interface boolRef extends Terminal
{
  /**
   * Returns the value of the '<em><b>Var Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var Ref</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Ref</em>' attribute.
   * @see #setVarRef(String)
   * @see org.xtext.labs.mydsl.MydslPackage#getboolRef_VarRef()
   * @model
   * @generated
   */
  String getVarRef();

  /**
   * Sets the value of the '{@link org.xtext.labs.mydsl.boolRef#getVarRef <em>Var Ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Ref</em>' attribute.
   * @see #getVarRef()
   * @generated
   */
  void setVarRef(String value);

} // boolRef
