/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.mydsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Do While Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.labs.mydsl.DoWhileExpression#getLoopConditon <em>Loop Conditon</em>}</li>
 *   <li>{@link org.xtext.labs.mydsl.DoWhileExpression#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.labs.mydsl.MydslPackage#getDoWhileExpression()
 * @model
 * @generated
 */
public interface DoWhileExpression extends BodyStatement
{
  /**
   * Returns the value of the '<em><b>Loop Conditon</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Loop Conditon</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loop Conditon</em>' containment reference.
   * @see #setLoopConditon(varExpression)
   * @see org.xtext.labs.mydsl.MydslPackage#getDoWhileExpression_LoopConditon()
   * @model containment="true"
   * @generated
   */
  varExpression getLoopConditon();

  /**
   * Sets the value of the '{@link org.xtext.labs.mydsl.DoWhileExpression#getLoopConditon <em>Loop Conditon</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Loop Conditon</em>' containment reference.
   * @see #getLoopConditon()
   * @generated
   */
  void setLoopConditon(varExpression value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.labs.mydsl.BodyStatement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference list.
   * @see org.xtext.labs.mydsl.MydslPackage#getDoWhileExpression_Body()
   * @model containment="true"
   * @generated
   */
  EList<BodyStatement> getBody();

} // DoWhileExpression
