/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.mydsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DSL Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.labs.mydsl.DSLProgram#getGlobal <em>Global</em>}</li>
 *   <li>{@link org.xtext.labs.mydsl.DSLProgram#getFunc <em>Func</em>}</li>
 *   <li>{@link org.xtext.labs.mydsl.DSLProgram#getMain <em>Main</em>}</li>
 * </ul>
 *
 * @see org.xtext.labs.mydsl.MydslPackage#getDSLProgram()
 * @model
 * @generated
 */
public interface DSLProgram extends EObject
{
  /**
   * Returns the value of the '<em><b>Global</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.labs.mydsl.varDeclared}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Global</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Global</em>' containment reference list.
   * @see org.xtext.labs.mydsl.MydslPackage#getDSLProgram_Global()
   * @model containment="true"
   * @generated
   */
  EList<varDeclared> getGlobal();

  /**
   * Returns the value of the '<em><b>Func</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.labs.mydsl.FuncDefinition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Func</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func</em>' containment reference list.
   * @see org.xtext.labs.mydsl.MydslPackage#getDSLProgram_Func()
   * @model containment="true"
   * @generated
   */
  EList<FuncDefinition> getFunc();

  /**
   * Returns the value of the '<em><b>Main</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Main</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Main</em>' containment reference.
   * @see #setMain(mainDeclared)
   * @see org.xtext.labs.mydsl.MydslPackage#getDSLProgram_Main()
   * @model containment="true"
   * @generated
   */
  mainDeclared getMain();

  /**
   * Sets the value of the '{@link org.xtext.labs.mydsl.DSLProgram#getMain <em>Main</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Main</em>' containment reference.
   * @see #getMain()
   * @generated
   */
  void setMain(mainDeclared value);

} // DSLProgram
