/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.mydsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Func Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.labs.mydsl.MydslPackage#getFuncParameter()
 * @model
 * @generated
 */
public interface FuncParameter extends varSymbol
{
} // FuncParameter
