/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.mydsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.labs.mydsl.MydslPackage
 * @generated
 */
public interface MydslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MydslFactory eINSTANCE = org.xtext.labs.mydsl.impl.MydslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>DSL Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DSL Program</em>'.
   * @generated
   */
  DSLProgram createDSLProgram();

  /**
   * Returns a new object of class '<em>main Declared</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>main Declared</em>'.
   * @generated
   */
  mainDeclared createmainDeclared();

  /**
   * Returns a new object of class '<em>Body Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Body Statement</em>'.
   * @generated
   */
  BodyStatement createBodyStatement();

  /**
   * Returns a new object of class '<em>var Return</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>var Return</em>'.
   * @generated
   */
  varReturn createvarReturn();

  /**
   * Returns a new object of class '<em>var Declared</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>var Declared</em>'.
   * @generated
   */
  varDeclared createvarDeclared();

  /**
   * Returns a new object of class '<em>var Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>var Expression</em>'.
   * @generated
   */
  varExpression createvarExpression();

  /**
   * Returns a new object of class '<em>Terminal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Terminal</em>'.
   * @generated
   */
  Terminal createTerminal();

  /**
   * Returns a new object of class '<em>var Symbol</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>var Symbol</em>'.
   * @generated
   */
  varSymbol createvarSymbol();

  /**
   * Returns a new object of class '<em>Terminal Or Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Terminal Or Method</em>'.
   * @generated
   */
  TerminalOrMethod createTerminalOrMethod();

  /**
   * Returns a new object of class '<em>array Dimension</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>array Dimension</em>'.
   * @generated
   */
  arrayDimension createarrayDimension();

  /**
   * Returns a new object of class '<em>Func Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Call</em>'.
   * @generated
   */
  FuncCall createFuncCall();

  /**
   * Returns a new object of class '<em>Func Parameter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Parameter</em>'.
   * @generated
   */
  FuncParameter createFuncParameter();

  /**
   * Returns a new object of class '<em>Func Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Definition</em>'.
   * @generated
   */
  FuncDefinition createFuncDefinition();

  /**
   * Returns a new object of class '<em>Abstract Method Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Method Call</em>'.
   * @generated
   */
  AbstractMethodCall createAbstractMethodCall();

  /**
   * Returns a new object of class '<em>Std Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Std Function</em>'.
   * @generated
   */
  StdFunction createStdFunction();

  /**
   * Returns a new object of class '<em>If Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>If Expression</em>'.
   * @generated
   */
  IfExpression createIfExpression();

  /**
   * Returns a new object of class '<em>Do While Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Do While Expression</em>'.
   * @generated
   */
  DoWhileExpression createDoWhileExpression();

  /**
   * Returns a new object of class '<em>Brk Str</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Brk Str</em>'.
   * @generated
   */
  BrkStr createBrkStr();

  /**
   * Returns a new object of class '<em>var Assignment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>var Assignment</em>'.
   * @generated
   */
  varAssignment createvarAssignment();

  /**
   * Returns a new object of class '<em>String Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Ref</em>'.
   * @generated
   */
  StringRef createStringRef();

  /**
   * Returns a new object of class '<em>num Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>num Ref</em>'.
   * @generated
   */
  numRef createnumRef();

  /**
   * Returns a new object of class '<em>bool Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>bool Ref</em>'.
   * @generated
   */
  boolRef createboolRef();

  /**
   * Returns a new object of class '<em>array Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>array Ref</em>'.
   * @generated
   */
  arrayRef createarrayRef();

  /**
   * Returns a new object of class '<em>var Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>var Ref</em>'.
   * @generated
   */
  varRef createvarRef();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MydslPackage getMydslPackage();

} //MydslFactory
