/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.mydsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Terminal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.labs.mydsl.MydslPackage#getTerminal()
 * @model
 * @generated
 */
public interface Terminal extends varExpression, TerminalOrMethod
{
} // Terminal
