/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.mydsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>var Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.labs.mydsl.varAssignment#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.labs.mydsl.varAssignment#getOp <em>Op</em>}</li>
 *   <li>{@link org.xtext.labs.mydsl.varAssignment#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.xtext.labs.mydsl.MydslPackage#getvarAssignment()
 * @model
 * @generated
 */
public interface varAssignment extends varExpression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Terminal)
   * @see org.xtext.labs.mydsl.MydslPackage#getvarAssignment_Left()
   * @model containment="true"
   * @generated
   */
  Terminal getLeft();

  /**
   * Sets the value of the '{@link org.xtext.labs.mydsl.varAssignment#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Terminal value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute list.
   * @see org.xtext.labs.mydsl.MydslPackage#getvarAssignment_Op()
   * @model unique="false"
   * @generated
   */
  EList<String> getOp();

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.labs.mydsl.TerminalOrMethod}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference list.
   * @see org.xtext.labs.mydsl.MydslPackage#getvarAssignment_Right()
   * @model containment="true"
   * @generated
   */
  EList<TerminalOrMethod> getRight();

} // varAssignment
