/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.mydsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>var Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.labs.mydsl.MydslPackage#getvarExpression()
 * @model
 * @generated
 */
public interface varExpression extends BodyStatement
{
} // varExpression
