/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.mydsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>var Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.labs.mydsl.varRef#getVarRef <em>Var Ref</em>}</li>
 * </ul>
 *
 * @see org.xtext.labs.mydsl.MydslPackage#getvarRef()
 * @model
 * @generated
 */
public interface varRef extends Terminal
{
  /**
   * Returns the value of the '<em><b>Var Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var Ref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Ref</em>' reference.
   * @see #setVarRef(varSymbol)
   * @see org.xtext.labs.mydsl.MydslPackage#getvarRef_VarRef()
   * @model
   * @generated
   */
  varSymbol getVarRef();

  /**
   * Sets the value of the '{@link org.xtext.labs.mydsl.varRef#getVarRef <em>Var Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Ref</em>' reference.
   * @see #getVarRef()
   * @generated
   */
  void setVarRef(varSymbol value);

} // varRef
