/*
 * generated by Xtext 2.12.0
 */
package org.xtext.labs


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MydslStandaloneSetup extends MydslStandaloneSetupGenerated {

	def static void doSetup() {
		new MydslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
