/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs;

import org.xtext.labs.MydslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MydslStandaloneSetup extends MydslStandaloneSetupGenerated {
  public static void doSetup() {
    new MydslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
