/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs;

import org.eclipse.xtext.generator.IGenerator2;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.xtext.labs.AbstractMydslRuntimeModule;
import org.xtext.labs.generator.MydslGenerator;
import org.xtext.labs.scoping.MydslNullGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MydslRuntimeModule extends AbstractMydslRuntimeModule {
  @Override
  public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
    return MydslNullGlobalScopeProvider.class;
  }
  
  public Class<? extends IGenerator2> bindIGenerator2() {
    return MydslGenerator.class;
  }
}
