/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.ui.labeling;

import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.resource.IReferenceDescription;
import org.eclipse.xtext.xbase.ui.labeling.XbaseDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class MydslDescriptionLabelProvider extends XbaseDescriptionLabelProvider {
  /**
   * @comment:kim
   * this label will be activate when you press ctrl + shift + g. when you try to find references of token.
   */
  @Override
  public Object text(final IEObjectDescription ele) {
    return ele.getName().toString();
  }
  
  @Override
  public Object text(final IReferenceDescription refDes) {
    return "matched result";
  }
  
  @Override
  public Object image(final IEObjectDescription ele) {
    return "dsl_view.gif";
  }
}
