/*
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.labs.parser.antlr.internal.InternalMydslParser;
import org.xtext.labs.services.MydslGrammarAccess;

public class MydslParser extends AbstractAntlrParser {

	@Inject
	private MydslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMydslParser createParser(XtextTokenStream stream) {
		return new InternalMydslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DSLProgram";
	}

	public MydslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MydslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
