/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.labs.MydslRuntimeModule;
import org.xtext.labs.MydslStandaloneSetup;
import org.xtext.labs.ide.MydslIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MydslIdeSetup extends MydslStandaloneSetup {
  @Override
  public Injector createInjector() {
    MydslRuntimeModule _mydslRuntimeModule = new MydslRuntimeModule();
    MydslIdeModule _mydslIdeModule = new MydslIdeModule();
    return Guice.createInjector(Modules2.mixin(_mydslRuntimeModule, _mydslIdeModule));
  }
}
