/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.ide;

import org.xtext.labs.ide.AbstractMydslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MydslIdeModule extends AbstractMydslIdeModule {
}
