/*
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.ui.wizard;

import org.eclipse.xtext.ui.wizard.XtextNewProjectWizard;

import org.eclipse.xtext.ui.wizard.IExtendedProjectInfo;
import org.eclipse.xtext.ui.wizard.IProjectCreator;
import com.google.inject.Inject;

public class MydslNewProjectWizard extends XtextNewProjectWizard {

	private MydslWizardNewProjectCreationPage mainPage;

	@Inject
	public MydslNewProjectWizard(IProjectCreator projectCreator) {
		super(projectCreator);
		setWindowTitle("New Mydsl Project");
	}

	protected MydslWizardNewProjectCreationPage getMainPage() {
		return mainPage;
	}

	/**
	 * Use this method to add pages to the wizard.
	 * The one-time generated version of this class will add a default new project page to the wizard.
	 */
	@Override
	public void addPages() {
		mainPage = createMainPage("basicNewProjectPage");
		mainPage.setTitle("Mydsl Project");
		mainPage.setDescription("Create a new Mydsl project.");
		addPage(mainPage);
	}

	protected MydslWizardNewProjectCreationPage createMainPage(String pageName) {
		return new MydslWizardNewProjectCreationPage(pageName);
	}

	/**
	 * Use this method to read the project settings from the wizard pages and feed them into the project info class.
	 */
	@Override
	protected IExtendedProjectInfo getProjectInfo() {
		MydslProjectInfo projectInfo = new MydslProjectInfo();
		projectInfo.setProjectName(mainPage.getProjectName());
		if (!mainPage.useDefaults()) {
			projectInfo.setLocationPath(mainPage.getLocationPath());
		}
		return projectInfo;
	}

}
