/*
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.labs.MydslRuntimeModule
import org.xtext.labs.MydslStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MydslIdeSetup extends MydslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MydslRuntimeModule, new MydslIdeModule))
	}
	
}
