/*
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractMydslScopeProvider extends XbaseBatchScopeProvider {
}
