/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.ui.outline;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.xtext.labs.mydsl.MydslPackage;
import org.xtext.labs.mydsl.varDeclared;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
@SuppressWarnings("all")
public class MydslOutlineTreeProvider extends DefaultOutlineTreeProvider {
  public boolean _isLeaf(final varDeclared pd) {
    return true;
  }
  
  @Override
  public void _createNode(final IOutlineNode parentNode, final EObject modelElement) {
    boolean filter = false;
    boolean _equals = modelElement.eClass().equals(MydslPackage.Literals.VAR_ASSIGNMENT);
    if (_equals) {
      filter = true;
    }
    if ((!filter)) {
      super._createNode(parentNode, modelElement);
    }
  }
}
