/*
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class MydslWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public MydslWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
