/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.mydsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.labs.mydsl.MydslPackage;
import org.xtext.labs.mydsl.TerminalOrMethod;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Terminal Or Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TerminalOrMethodImpl extends MinimalEObjectImpl.Container implements TerminalOrMethod
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TerminalOrMethodImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MydslPackage.Literals.TERMINAL_OR_METHOD;
  }

} //TerminalOrMethodImpl
