/**
 * generated by Xtext 2.12.0
 */
package org.xtext.labs.mydsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.labs.mydsl.MydslPackage;
import org.xtext.labs.mydsl.varExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>var Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class varExpressionImpl extends BodyStatementImpl implements varExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected varExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MydslPackage.Literals.VAR_EXPRESSION;
  }

} //varExpressionImpl
